name: Github Release

on:
  push:
    branches:
      - "master"
      - "dev"
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - "master"
      - "dev"
    tags:
      - "*.*.*"

jobs:
  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o github_action_example_linux_amd64 .
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o github_action_example_windows_amd64.exe .
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o github_action_example_darwin_amd64 .

      - run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o github_action_example_linux_arm64 .
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -o github_action_example_windows_arm64.exe .
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o github_action_example_darwin_arm64 .

      # https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            github_action_example_linux_amd64
            github_action_example_windows_amd64.exe
            github_action_example_darwin_amd64
            github_action_example_linux_arm64
            github_action_example_windows_arm64.exe
            github_action_example_darwin_arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
