name: Github Release

on:
  push:
    branches:
      - "master"
      - "dev"
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - "master"
      - "dev"
    tags:
      - "*.*.*"

jobs:
  release:
    # if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      - run: go test ./... -race -coverpkg=./... -coverprofile=coverage.txt -v

      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage.txt # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o github_action_example_linux_amd64 .
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o github_action_example_windows_amd64.exe .
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o github_action_example_darwin_amd64 .

      - run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o github_action_example_linux_arm64 .
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -o github_action_example_windows_arm64.exe .
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o github_action_example_darwin_arm64 .

      # https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            github_action_example_linux_amd64
            github_action_example_windows_amd64.exe
            github_action_example_darwin_amd64
            github_action_example_linux_arm64
            github_action_example_windows_arm64.exe
            github_action_example_darwin_arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



      - name: Generate release tag
        if: "!startsWith(github.ref, 'refs/tags/')"
        id: tag
        run: |
          echo "::set-output name=release_tag::${{ github.sha::8 }}"

      - name: dev Release
        uses: softprops/action-gh-release@v1
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          files: |
            github_action_example_linux_amd64
            github_action_example_windows_amd64.exe
            github_action_example_darwin_amd64
            github_action_example_linux_arm64
            github_action_example_windows_arm64.exe
            github_action_example_darwin_arm64
          tag_name: ${{ steps.tag.outputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}